# fizz
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fizz-dp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fizz
  template:
    metadata:
      name: fizz
      labels:
        app: fizz
        release: beta
    spec:
      containers:
        - image: tarek5/fizz
          imagePullPolicy: Always
          name: fizz
          ports:
            - name: restapi
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
          env:
            - name: HTTP_PORT
              value: "5000"
            - name: EMAIL_BACKEND
              value: "mailgun"
            - name: MAILGUN_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: fizz-secrets
                  key: mailgun-domain
            - name: MAILGUN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: fizz-secrets
                  key: mailgun-api-key
---
apiVersion: v1
kind: Service
metadata:
  name: fizz-svc
spec:
  type: NodePort
  selector:
    app: fizz
  ports:
    - port: 9000
      targetPort: restapi
      nodePort: 30123
---
# prometheus
apiVersion: v1
kind: Deployment
metadata:
  name: prometheus-dp
spec:
  selector:
    matchLabels:
      app: prometheus
  replicas: 1
  template:
    metadata:
      name: prometheus-pod
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus-container
          image: prom/prometheus
          ports:
            - name: prometheusport
              containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: prometheusport
      nodePort: 30124
