apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: fizz-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fizz
  template:
    metadata:
      name: fizz
      labels:
        app: fizz
        release: beta
    spec:
      containers:
        - image: tarek5/fizz
          imagePullPolicy: Always
          name: fizz
          ports:
            - name: restapi
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: fizz-svc
spec:
  type: NodePort
  selector:
    app: fizz
  ports:
    - port: 9000
      targetPort: restapi
      nodePort: 30123
